name: Persistent VM with Dockerfile

on:
  workflow_dispatch:

jobs:
  run-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download disk if exists
      uses: actions/download-artifact@v4
      with:
        name: vm-disk
      continue-on-error: true

    - name: docker run --privileged -p 6080:6080 -p 2221:2222 -v $PWD/vmdata:/data arindamvm/githubvm
      run: docker run --privileged -p 6080:6080 -p 2221:2222 -v $PWD/vmdata:/data arindamvm/githubvm

    - name: Create disk if not exists
      run: |
        if [ ! -f disk.img ]; then
          qemu-img create -f qcow2 disk.img 400G
        fi

    - name: Run VM container with mounted disk
      run: |
        docker run --rm -v $PWD/disk.img:/data/disk.img my-vm

    - name: Upload disk after run (persist data)
      uses: actions/upload-artifact@v4
      with:
        name: vm-disk
        path: disk.img
